### ISSUE TITLE
overwrite nodeSelector for jobs

### ISSUE THREAD

**Issue by ghebo** [woodpecker-ci/helm#105]
Pod that should execute a job got 
`Node-Selectors:              kubernetes.io/arch=amd64`

while nodes in GKE with Kubernetes version: v1.26.6-gke.1700 are labeled  `beta.kubernetes.io/arch=amd64`

.woodpecker.yml

```
pipeline:
  dummy-job:
    image: busybox
    commands:
      - echo "Dummy pipeline"
    backend_options:
      kubernetes:
        nodeSelector:
          beta.kubernetes.io/arch: amd64
```

          
          
values.yaml

```
    agent:
      image:
        tag: "v1.0.0"
      env:
        WOODPECKER_AGENT_SECRET: "aaaaaaa"
        WOODPECKER_SERVER: "woodpecker-server.woodpecker.svc.cluster.local:9000"
        WOODPECKER_BACKEND: kubernetes
        WOODPECKER_BACKEND_K8S_NAMESPACE: woodpecker
      nodeSelector: 
        beta.kubernetes.io/arch: amd64
```

In the documentation is mentioned:

> Labels defined here will be appended to a list already containing "kubernetes.io/arch". By default the pod will use "kubernetes.io/arch" inferred from top-level "platform" setting which is deducted from the agents' environment variable CI_SYSTEM_PLATFORM. To overwrite this, you need to specify this label in the nodeSelector section.

The question is how to remove that default label, and add **beta**.kubernetes.io/arch=amd64

**Comment by pat-s** [comment]
Which WP version are you using?

```yml
    backend_options:
      kubernetes:
        nodeSelector:
          beta.kubernetes.io/arch: amd64
```

will set set label. To remove it, just remove it from the pipeline definition. Otherwise I don't understand your question...
