### ISSUE TITLE
Bad indent setting for extraVolumes?

### ISSUE THREAD

**Issue by dominic-p** [woodpecker-ci/helm#118]
This is a follow up from #97. In my testing, it looks like the extra volume mounts are added at the wrong indent level which breaks the YAML and the entire chart. If I run `helm template ...` I get YAML that looks like this:

```yaml
# Source: woodpecker/charts/server/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: woodpecker-server
spec:
  serviceName: woodpecker-server-headless
  template:
    spec:
      serviceAccountName: default
      securityContext:
        {}
      containers:
        - name: server
          securityContext:
            {}
          image: "docker.io/woodpeckerci/woodpecker-server:next"
          imagePullPolicy: IfNotPresent
          resources:
            {}
          volumeMounts:
          - name: data
            mountPath: /var/lib/woodpecker
            - mountPath: /etc/registry
              name: reg-cred
              readOnly: true
          env:
            - name: ...
          
```

I removed some irrelevant parts for clarity. You can see that the `mountPath` stanza is indented a bit too far.
