### ISSUE TITLE
Can't upgrade to 1.1.0 using helm controller

### ISSUE THREAD

**Issue by vyskocilm** [woodpecker-ci/helm#153]
Hi,

congrats to https://github.com/woodpecker-ci/helm/releases/tag/1.1.0 release. Sadly I have issues updating it in my k3s system. I use k3s helm-controller, however following definition fails

```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: woodpecker
  namespace: woodpecker
spec:
  version: 1.1.0
  chart: woodpecker
  repo: https://woodpecker-ci.org/
  targetNamespace: woodpecker
```

When running helm locally all I see is 1.0.3

```sh
$ helm repo list
NAME                    URL                                    
...
woodpecker              https://woodpecker-ci.org/ 
$ helm repo update 
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "woodpecker" chart repository
Update Complete. ⎈Happy Helming!⎈
$ helm search repo woodpecker --versions
NAME                    CHART VERSION   APP VERSION     DESCRIPTION                   
woodpecker/woodpecker   1.0.3           2.1.1           A Helm chart for Woodpecker CI
woodpecker/woodpecker   1.0.2           2.1.0           A Helm chart for Woodpecker CI
...
```

BTW: noticed the artifactory lists 1.0.3 as the last version too https://artifacthub.io/api/v1/packages/helm/woodpecker-ci/woodpecker/feed/rss
