### ISSUE TITLE
Helm template error when upgrading to 1.2.x

### ISSUE THREAD

**Issue by telcmege** [woodpecker-ci/helm#182]
### Steps to reproduce
- Use version `1.2.0` or higher from `https://woodpecker-ci.org/`
- Set the `woopecker.agent.prersistence.enabled` to `true`
- Configure a volume in `woodpecker.agent.extraVolumes` and `woodpecker.agent.extraVolumeMounts`

### Descripition
When `woodpecker.agent.extraVolumes` and `woodpecker.agent.extraVolumeMounts` are configured, and `woodpecker.agent.persistence` is set to `true`, an error occurs when parsing the helm templates.

> Error: YAML parse error on woodpecker/charts/woodpecker/charts/agent/templates/statefulset.yaml: error converting YAML to JSON: yaml: line 42: did not find expected '-' indicator
helm.go:84: [debug] error converting YAML to JSON: yaml: line 42: did not find expected '-' indicator
YAML parse error on woodpecker/charts/woodpecker/charts/agent/templates/statefulset.yaml

#### My agent config
```
woodpecker:    
  agent:    
    enabled: true    
    replicaCount: 2    
    image:    
      tag: v2.4.1-alpine    
    persistence:    
      enabled: true    
    extraVolumes:    
      - name: ca-pemstore    
        configMap:    
          name: ca-pemstore    
    extraVolumeMounts:    
      - name: ca-pemstore    
        mountPath: /etc/ssl/certs/CustomCA.pem    
        subPath: CustomCA.pem    
    extraSecretNamesForEnvFrom:    
      - agent-env
```
