### ISSUE TITLE
Prometheus Operator CRDs - ServiceMonitor

### ISSUE THREAD

**Issue by genofire** [woodpecker-ci/helm#21]
it would be nice, that this helmcharts deploy also a ServiceMonitor, which select all Service (and there behind all Pods) to scrape all Metrics.

https://prometheus-operator.dev/docs/operator/api/#monitoring.coreos.com/v1.ServiceMonitor

**Comment by genofire** [comment]
add option to generate Secret for `WOODPECKER_PROMETHEUS_AUTH_TOKEN`

---

new values:
```yaml
prometheus:
  servicemonitor:
    enabled: false
    labels: {}
  rules:
    enabled: false
    labels: {}
    additionalRules: []
  
grafana:
  dashboards:
    enabled: false
    labels:
      grafana_dashboard: "1"
    annotations: {}
```

Values usage e.g.:

```yaml
prometheus:
  servicemonitor:
    enabled: true
    labels:
      release: "kube-prometheus-stack"
  rules:
    # will deploy alert rules
    enabled: true
    labels:
      release: "kube-prometheus-stack"
    additionalRules: []
grafana:
  dashboards:
    enabled: true
```

PS: The labels `release=kube-prometheus-stack` is setup with the helmchart of the Prometheus Operator.

---

ServiceMonitor:
```yaml
{{- if and .Values.prometheus.servicemonitor.enabled ( .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" ) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "helmchart.fullname" . }}
  labels:
    {{- include "helmchart.labels" . | nindent 4 }}
    {{- with .Values.prometheus.servicemonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  endpoints:
    - port: http
      path: /metrics
      basicAuth:
        username:
          name: "secretName"
          key: "WOODPECKER_PROMETHEUS_AUTH_TOKEN"
  selector:
    matchLabels:
      {{- include "helmchart.selectorLabels" . | nindent 6 }}
{{- end }}
```

Prometheus-Rules:

```yaml
{{- if and .Values.prometheus.rules.enabled ( .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" ) }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "helmchart.fullname" . }}
  labels:
    {{- include "helmchart.labels" . | nindent 4 }}
    {{- with .Values.prometheus.rules.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  groups:
  {{- if .Values.prometheus.rules.additionalRules }}
  - name: {{ template "helmchart.fullname" . }}-Additional
    rules: {{- toYaml .Values.prometheus.rules.additionalRules | nindent 4 }}
  {{- end }}
{{- end }}
```

ConfigMap for Grafana Dashboard ( for everyfile in `grafana_dashboards` one, because of the 1MB limit of etcd):

```yaml
{{- if .Values.grafana.dashboards.enabled }}
{{- range $path, $bytes := .Files.Glob "grafana_dashboards/*.json" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helmchart.fullname" $ }}-grafana-dashboards-{{ base $path }}
  labels:
    {{- include "mollysocket.labels" $ | nindent 4 }}
    {{- with $.Values.grafana.dashboards.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml $.Values.grafana.dashboards.annotations | nindent 4 }}
data:
  {{- ($.Files.Glob $path ).AsConfig | nindent 2 }}
{{- end }}
{{- end }}
```
