### ISSUE TITLE
[question] pvc claim fails on k3s

### ISSUE THREAD

**Issue by aphilas** [woodpecker-ci/helm#44]
I am using the [helm chart](https://github.com/woodpecker-ci/helm) and the [docs](https://woodpecker-ci.org/docs/next/administration/kubernetes) to get started on k3s. Following the [docs](https://docs.k3s.io/storage), I have changed `server.persistentVolume.storageClass` to `local-path`. The server is stuck at pending with `1 pod has unbound immediate PersistentVolumeClaims`. I have futilely tried to create a persistent volume manually. Admittedly, I am pretty new to the k8s ecosystem, and I might have missed some _simple_ step.

<details>
<summary>myvalues.yml</summary>

```yml
agent:
  # -- The number of replicas for the deployment
  replicaCount: 1

  image:
    # -- Overrides the image tag whose default is the chart appVersion.
    tag: ""

  env:
    # -- Add the environment variables for the agent component
    WOODPECKER_BACKEND_K8S_VOLUME_SIZE: 5G

server:
  image:
    tag: ""

  # -- Add environment variables for the server component
  env:
    WOODPECKER_ADMIN: "aphilas"
    WOODPECKER_HOST: "https://ci.example.org"
    WOODPECKER_GITHUB: "true"

  persistentVolume:
    # -- Defines the size of the persistent volume
    size: 5Gi
    # -- Defines the storageClass of the persistent volume
    storageClass: "local-path"
    # -- Defines the path where the volume should be mounted
    # mountPath: "/var/lib/woodpecker"
    mountPath: null

  service:
    # -- The port of the service
    port: &servicePort 80

  ingress:
    # -- Enable the ingress for the server component
    enabled: true
    # -- Add annotations to the ingress
    annotations:
      kubernetes.io/ingress.class: traefik
      cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd

    hosts:
      - host: ci.example.org
        paths:
          - path: /
            backend:
              serviceName: ci.example.org
              servicePort: *servicePort
    tls:
      - secretName: woodpecker-tls
        hosts:
          - ci.example.org
```

</details>

```sh
helm upgrade --install -f myvalues.yml woodpecker-server woodpecker/woodpecker-server
```

[Original message on Matrix](https://matrix.to/#/!vbfAJmueDTbflXuvif:obermui.de/$bKhY4N0g5rfOUoQ4mTkOsHNcnNn1wQ-RL3yMWK_tmLs?via=obermui.de&via=matrix.org&via=t2bot.io)

**Comment by pat-s** [comment]
Does the SC `local-path` exist?

You should be able to get more information on why the PVC is stuck in "pending" by describing it via `kubectl`. This might eventually help you to resolve the issue on your own. 

It's not a chart issue but a user one.

**Comment by aphilas** [comment]
Thanks for the pointers.

Yes, the sc `local-path` exists. 

`describe`-ing the pvc yields `persistentvolume-controller  storageclass.storage.k8s.io "gp2" not found`. Shouldn't it use my custom value `local-path`? Would that have to do with the helm chart or is that a different issue?

**Comment by aphilas** [comment]
The "issue" was that the values must be top-level items in the yaml, rather than my erroneous structure (I simply edited [values.yaml](https://github.com/woodpecker-ci/helm/blob/main/values.yaml)):

```yaml
agent:
    # ...
server:
    # ...
```
