### ISSUE TITLE
missing secret 

### ISSUE THREAD

**Issue by ashtonian** [woodpecker-ci/helm#73]
Deploying from tf. It would be nice if the secret creation was optional, so the chart worked out of the box. I think the secret references in the [.values](https://github.com/woodpecker-ci/helm/blob/main/values.yaml#L52) should likely just be a comment.  

Alternatively it could be optionally created:
```yaml
{{- if .Values.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
type: Opaque
{{- end }}
```

Could also be a pre chart hook to create if not present:
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: pre-install-secret-check
  annotations:
    "helm.sh/hook": pre-install
spec:
  template:
    spec:
      containers:
      - name: check-secret
        image: appropriate-image
        command: ["/bin/sh"]
        args: ["-c", "upsert_secret.sh"]
      restartPolicy: OnFailure
```
