### ISSUE TITLE
allow `extraVolumeMounts` without enabling default persistentVolume

### ISSUE THREAD

**Issue by pat-s** [woodpecker-ci/helm#97]
_Originally posted by @genofire in https://github.com/woodpecker-ci/helm/pull/94#discussion_r1358218931_

**Comment by pat-s** [comment]
Might be a false-positive

**Comment by genofire** [comment]
This should be open again, still not fixed.

**Comment by genofire** [comment]
just try this `broken-values.yaml`
```yaml
server:
  resources:
    requests:
      cpu: "500m"
      memory: "200m"
  persistentVolume:
    enabled: false
  extraVolumes:                                                                                                                                                                                                                                                                                              
    - name: docker-config
      configMap:
        name: docker-config
  extraVolumeMounts:
    - name: docker-config
      mountPath: /etc/docker
```
